title: Uche's site
author: Uche Emordi
email: emordiuche@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My first ever github page

# social links
twitter_username: emordi_u
github_username:  emordiuche

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
